config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as:'about'
  get 'pages/about' => 'pages#about'
  get 'new' => 'posts#new'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  #http_basic_authenticate_with name: "admin", password: "password", only: [:destroy]
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    
    redirect_to post_path(@post)
    
    #if(@comment.save)
    #  redirect_to post_path(@post)
    #else
    #  render 'posts/show'
    #end
    
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us';
    @content = 'This is about us.' 
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  #http_basic_authenticate_with name: "brad", password: "1234", except: [:index, :show]
  
  def index
    @title = 'Posts';
    @content = 'Here are the posts.' 
    @posts = Post.all
  end
  
  def show
    @post= Post.find(params[:id])
  end
  
  def new
    @title = 'New Post';
    @content = 'Make new post here.' 
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
    @title = 'Edit Post';
    @content = 'Edit post here.' 
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
     @post = Post.find(params[:id])
     @post.destroy
     redirect_to posts_path
  end
  
  private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<h3>Comments</h3>

<% @post.comments.each do |comment| %>
	<div class="container">
		<p>
			<strong><%= comment.title %></strong>: <%= comment.body %>
			<%= link_to '[X]', [comment.post, comment],
				method: :delete,
				data: { confirm: "Are you sure?"} %>
		</p>		
		
	</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
	
	<p>
		<%= f.label :title %>
		<%= f.text_field(:title, {:class => "form-control"})%>
	</p>
	<p>
		<%= f.label :body %>
		<%= f.text_area(:body, {:class => "form-control"})%>
	</p>
	<p>
		<%= f.submit(:submit, {:class => "btn btn-secondary my-2 my-sm-0"})%>
	</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>The Second Test Blog</title>
		<%= csrf_meta_tags %>
	    <%= csp_meta_tag %>
		<%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	
	<body> 
		 <div class="container">	
			<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			  	<a class="navbar-brand">Test Blog 2</a>
			  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			    	<span class="navbar-toggler-icon"></span>
			  	</button>
			
				<div class="collapse navbar-collapse" id="navbarsExampleDefault">
					<ul class="navbar-nav mr-auto">
					  <li class="nav-item active">
					    <a class="nav-link" href=<%= home_path %>>Home</a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link" href=<%= new_post_path%>>New</a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link" href=<%= about_path%>>About</a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">coming soon</a>
					  </li>				  
					</ul>
					<form class="form-inline my-2 my-lg-0">
						<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
				  		<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
					</form>
					
				</div> 				 
			</nav>			
		</div>	
		<p>..</p>
		<p>..</p>
		<div class="container">
				<%= yield %>
		</div>
		
	</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1> <!--Header-->
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1><%= @title %></h1> <!--Header-->
<p><%= @content %></p>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title, :class => 'form-control' %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_field :body, :class => 'form-control' %>
	</p>	
	<p>
		<%= f.submit :class => 'btn btn-primary' %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1><%= @title %></h1> <!--Header-->
<p><%= @content %></p>


	<% @posts.each do |post| %>
		<div class="wrapper">
			<div class="container-fluid">
				<h3><%= post.title %></h3>
				<p><%= post.body %></p>
				
				<a class="btn btn-secondary my-2 my-sm-0" href=<%= post_path(post)%>>Read More</a>
			</div>
		</div>
		<hr>
	<%end%>

app/views/posts/new.html.erb
<h1><%= @title %></h1> <!--Header-->
<p><%= @content %></p>

<%= form_for :post, url: posts_path do |f| %>
	
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title, :class => 'form-control' %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_field :body, :class => 'form-control' %>
	</p>	
	<p>
		<%= f.submit :class => 'btn btn-primary' %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>

<%= link_to "edit", edit_post_path(@post), :class => "btn btn-secondary my-2 my-sm-0"%>
<%= link_to "delete", post_path(@post),
	method: :delete,
	data: {confirm: "Are you sure"},
	:class => "btn btn-danger my-2 my-sm-0" %>

<hr>

<%= render 'comments/comment' %>
<%= render 'comments/form' %>